name: CI Security Audit

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
 
      - name: Check binary entropy
        run: |
          chmod +x scripts/analyze_entropy.py
          python3 scripts/analyze_entropy.py data/optimized_kernel_weights.bin

 
      - name: Build Code
        run: |
          mkdir -p build
          g++ -std=c++23 -c src/main.cpp -o build/app.o
